import type { Part } from './types';

export const partsData: Part[] = [
  {
    id: 'ROP-0001',
    name: 'AquaPure Membrane 100GPD',
    name_hi: 'एक्वाप्योर मेम्ब्रेन 100GPD',
    price: 2500,
    discountPrice: 2250,
    description: 'A high-quality RO membrane with a 100 GPD capacity, ensuring high rejection rates and long-lasting performance for pure, safe drinking water.',
    description_hi: 'एक उच्च-गुणवत्ता वाली आरओ मेम्ब्रेन जिसकी क्षमता 100 GPD है, जो शुद्ध और सुरक्षित पीने के पानी के लिए उच्च अस्वीकृति दर और लंबे समय तक चलने वाले प्रदर्शन को सुनिश्चित करती है।',
    image: 'https://placehold.co/400x400.png',
    category: 'Membranes',
    category_hi: 'मेम्ब्रेन',
    features: 'High rejection rate, Long lifespan',
    features_hi: 'उच्च अस्वीकृति दर, लंबी उम्र',
    minQuantity: 1,
  },
  {
    id: 'ROP-0002',
    name: 'HydroFlow Sediment Filter',
    name_hi: 'हाइड्रोफ्लो सेडिमेंट फ़िल्टर',
    price: 550,
    description: '5-micron sediment filter that effectively removes sand, silt, rust, and other suspended particles to protect your RO system.',
    description_hi: '5-माइक्रोन का सेडिमेंट फ़िल्टर जो आपके आरओ सिस्टम की सुरक्षा के लिए रेत, गाद, जंग और अन्य निलंबित कणों को प्रभावी ढंग से हटाता है।',
    image: 'https://placehold.co/400x400.png',
    category: 'Filters',
    category_hi: 'फ़िल्टर',
    features: 'NSF certified, Easy installation',
    features_hi: 'NSF प्रमाणित, आसान इंस्टॉलेशन',
    minQuantity: 1,
  },
  {
    id: 'ROP-0003',
    name: 'PureStream Booster Pump',
    name_hi: 'प्योरस्ट्रीम बूस्टर पंप',
    price: 4500,
    discountPrice: 4000,
    description: 'Powerful and quiet booster pump to increase water pressure for optimal RO membrane performance, suitable for low-pressure areas.',
    description_hi: 'शक्तिशाली और शांत बूस्टर पंप जो कम दबाव वाले क्षेत्रों के लिए उपयुक्त है और आरओ मेम्ब्रेन के શ્રેષ્ઠ प्रदर्शन के लिए पानी का दबाव बढ़ाता है।',
    image: 'https://placehold.co/400x400.png',
    category: 'Pumps',
    category_hi: 'पंप',
    features: 'Durable material, Low energy consumption',
    features_hi: 'टिकाऊ सामग्री, कम ऊर्जा की खपत',
    minQuantity: 1,
  },
  {
    id: 'ROP-0004',
    name: 'EcoWater Solenoid Valve',
    name_hi: 'इकोवाटर सोलनॉइड वाल्व',
    price: 800,
    description: 'Reliable 24V DC solenoid valve to automatically control water flow, preventing wastage and ensuring efficient operation.',
    description_hi: 'विश्वसनीय 24V DC सोलनॉइड वाल्व जो पानी के प्रवाह को स्वचालित रूप से नियंत्रित करता है, बर्बादी को रोकता है और कुशल संचालन सुनिश्चित करता है।',
    image: 'https://placehold.co/400x400.png',
    category: 'Valves',
    category_hi: 'वाल्व',
    features: 'Leak-proof design, Universal compatibility',
    features_hi: 'रिसाव-रोधी डिज़ाइन, सार्वभौमिक संगतता',
    minQuantity: 1,
  },
  {
    id: 'ROP-0005',
    name: 'MaxFlow 1/4" Fitting',
    name_hi: 'मैक्सफ्लो 1/4" फिटिंग',
    price: 150,
    discountPrice: 120,
    description: 'Quick-connect 1/4 inch elbow fitting for secure, leak-free connections between RO components. Made from food-grade plastic.',
    description_hi: 'आरओ घटकों के बीच सुरक्षित, रिसाव-मुक्त कनेक्शन के लिए त्वरित-कनेक्ट 1/4 इंच एल्बो फिटिंग। खाद्य-ग्रेड प्लास्टिक से बना है।',
    image: 'https://placehold.co/400x400.png',
    category: 'Fittings',
    category_hi: 'फिटिंग्स',
    features: 'High flow rate, High rejection rate',
    features_hi: 'उच्च प्रवाह दर, उच्च अस्वीकृति दर',
    minQuantity: 10,
  },
  {
    id: 'ROP-0006',
    name: 'UltraSafe Membrane Housing',
    name_hi: 'अल्ट्रासेफ मेम्ब्रेन हाउसिंग',
    price: 1200,
    description: 'Durable, high-pressure membrane housing compatible with standard residential RO membranes. Includes O-rings for a perfect seal.',
    description_hi: 'टिकाऊ, उच्च दबाव वाली मेम्ब्रेन हाउसिंग जो मानक आवासीय आरओ मेम्ब्रेन के साथ संगत है। एक आदर्श सील के लिए ओ-रिंग्स शामिल हैं।',
    image: 'https://placehold.co/400x400.png',
    category: 'Housing',
    category_hi: 'हाउसिंग',
    features: 'Long lifespan, NSF certified',
    features_hi: 'लंबी उम्र, NSF प्रमाणित',
    minQuantity: 1,
  },
  {
    id: 'ROP-0007',
    name: 'AquaPure Carbon Block Filter',
    name_hi: 'एक्वाप्योर कार्बन ब्लॉक फ़िल्टर',
    price: 750,
    discountPrice: 650,
    description: 'Activated carbon block filter that removes chlorine, tastes, and odors to improve water quality and taste.',
    description_hi: 'सक्रिय कार्बन ब्लॉक फ़िल्टर जो पानी की गुणवत्ता और स्वाद में सुधार के लिए क्लोरीन, स्वाद और गंध को हटाता है।',
    image: 'https://placehold.co/400x400.png',
    category: 'Filters',
    category_hi: 'फ़िल्टर',
    features: 'Easy installation, Durable material',
    features_hi: 'आसान इंस्टॉलेशन, टिकाऊ सामग्री',
    minQuantity: 1,
  },
  {
    id: 'ROP-0008',
    name: 'HydroFlow Auto Flush Valve',
    name_hi: 'हाइड्रोफ्लो ऑटो फ्लश वाल्व',
    price: 600,
    description: 'An automatic flush valve that periodically rinses the membrane to prevent scaling and prolong its life.',
    description_hi: 'एक स्वचालित फ्लश वाल्व जो स्केलिंग को रोकने और मेम्ब्रेन के जीवन को बढ़ाने के लिए समय-समय पर मेम्ब्रेन को धोता है।',
    image: 'https://placehold.co/400x400.png',
    category: 'Valves',
    category_hi: 'वाल्व',
    features: 'Low energy consumption, Leak-proof design',
    features_hi: 'कम ऊर्जा की खपत, रिसाव-रोधी डिज़ाइन',
    minQuantity: 1,
  },
  {
    id: 'ROP-0009',
    name: 'PureStream UV Sterilizer',
    name_hi: 'प्योरस्ट्रीम यूवी स्टेरिलाइज़र',
    price: 3500,
    description: 'UV sterilizer lamp and chamber to eliminate up to 99.99% of bacteria, viruses, and other microorganisms.',
    description_hi: '99.99% तक बैक्टीरिया, वायरस और अन्य सूक्ष्मजीवों को खत्म करने के लिए यूवी स्टेरिलाइज़र लैंप और कक्ष।',
    image: 'https://placehold.co/400x400.png',
    category: 'Sterilizers',
    category_hi: 'स्टेरिलाइज़र',
    features: 'Universal compatibility, High flow rate',
    features_hi: 'सार्वभौमिक संगतता, उच्च प्रवाह दर',
    minQuantity: 1,
  },
  {
    id: 'ROP-0010',
    name: 'EcoWater Mineral Cartridge',
    name_hi: 'इकोवाटर मिनरल कार्ट्रिज',
    price: 900,
    discountPrice: 800,
    description: 'Adds essential minerals back into the purified water to improve taste and provide health benefits.',
    description_hi: 'स्वाद में सुधार और स्वास्थ्य लाभ प्रदान करने के लिए शुद्ध पानी में आवश्यक खनिजों को वापस मिलाता है।',
    image: 'https://placehold.co/400x400.png',
    category: 'Filters',
    category_hi: 'फ़िल्टर',
    features: 'High rejection rate, Long lifespan',
    features_hi: 'उच्च अस्वीकृति दर, लंबी उम्र',
    minQuantity: 1,
  },
  ...Array.from({ length: 40 }, (_, i) => {
    const id = i + 11;
    const categories = ['Membranes', 'Filters', 'Pumps', 'Valves', 'Fittings', 'Housing', 'Sterilizers'];
    const categories_hi = ['मेम्ब्रेन', 'फ़िल्टर', 'पंप', 'वाल्व', 'फिटिंग्स', 'हाउसिंग', 'स्टेरिलाइज़र'];
    const names = ['AquaPure', 'HydroFlow', 'PureStream', 'EcoWater', 'MaxFlow', 'UltraSafe'];
    const names_hi = ['एक्वाप्योर', 'हाइड्रोफ्लो', 'प्योरस्ट्रीम', 'इकोवाटर', 'मैक्सफ्लो', 'अल्ट्रासेफ'];
    const category = categories[id % categories.length];
    const category_hi = categories_hi[id % categories_hi.length];
    const price = Math.floor(Math.random() * (9000 - 500 + 1)) + 500;
    const hasDiscount = Math.random() > 0.7; // 30% chance of having a discount
    return {
      id: `ROP-${String(id).padStart(4, '0')}`,
      name: `${names[id % names.length]} ${category.slice(0, -1)} ${Math.floor(Math.random() * 1000)}`,
      name_hi: `${names_hi[id % names_hi.length]} ${category_hi} ${Math.floor(Math.random() * 1000)}`,
      price: price,
      discountPrice: hasDiscount ? Math.floor(price * (Math.random() * (0.9 - 0.7) + 0.7)) : undefined,
      description: 'A high-quality RO part designed for performance and durability. Ideal for various water purification systems.',
      description_hi: 'प्रदर्शन और स्थायित्व के लिए डिज़ाइन किया गया एक उच्च-गुणवत्ता वाला आरओ पार्ट। विभिन्न जल शोधन प्रणालियों के लिए आदर्श।',
      image: 'https://placehold.co/400x400.png',
      category: category,
      category_hi: category_hi,
      features: 'Standard feature set, reliable performance',
      features_hi: 'मानक सुविधा सेट, विश्वसनीय प्रदर्शन',
      minQuantity: 1,
    };
  }),
];
