
import type { Part } from './types';

export const partsData: Part[] = [
  // A1. Domestic RO Membranes
  {
    id: 'DOM-MEM-001',
    name: '75 GPD RO Membrane - Generic',
    name_hi: '75 जीपीडी आरओ मेम्ब्रेन - जेनेरिक',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 900,
    description: 'Standard 75 GPD replacement RO membrane. Fits all standard domestic RO purifiers.',
    description_hi: 'मानक 75 जीपीडी प्रतिस्थापन आरओ मेम्ब्रेन। सभी मानक घरेलू आरओ प्यूरीफायर में फिट होती है।',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '75 GPD Flow Rate, High Salt Rejection, Universal Fit',
    gpd: 75,
  },
  {
    id: 'DOM-MEM-002',
    name: '80 GPD RO Membrane - Generic',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 950,
    description: 'Standard 80 GPD replacement RO membrane. Fits all standard domestic RO purifiers.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '80 GPD Flow Rate, High Salt Rejection, Universal Fit',
    gpd: 80,
  },
  {
    id: 'DOM-MEM-003',
    name: '100 GPD RO Membrane - Generic',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 1100,
    description: 'High-flow 100 GPD replacement RO membrane for faster water purification.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '100 GPD Flow Rate, High Salt Rejection, Universal Fit',
    gpd: 100,
  },
  {
    id: 'DOM-MEM-004',
    name: '75 GPD RO Membrane - Vontron Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Vontron',
    price: 1400,
    description: 'Genuine Vontron 75 GPD RO membrane known for its reliability and high performance.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '75 GPD, 98% Salt Rejection, Long-lasting Durability',
    gpd: 75,
  },
  {
    id: 'DOM-MEM-005',
    name: '80 GPD RO Membrane - Vontron Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Vontron',
    price: 1500,
    discountPrice: 1350,
    description: 'Genuine Vontron 80 GPD RO membrane known for its reliability and high performance.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '80 GPD, 98% Salt Rejection, Long-lasting Durability',
    gpd: 80,
  },
  {
    id: 'DOM-MEM-006',
    name: '100 GPD RO Membrane - Vontron Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Vontron',
    price: 1650,
    description: 'Genuine Vontron 100 GPD high-flow RO membrane.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '100 GPD, 98% Salt Rejection, High-Flow',
    gpd: 100,
  },
  {
    id: 'DOM-MEM-007',
    name: '75 GPD RO Membrane - Dow Filmtec Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Dow Filmtec',
    price: 2200,
    description: 'Premium Dow Filmtec 75 GPD membrane, the industry standard for quality and performance.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'Genuine Dow Product, 99% Rejection, Trusted Performance',
    gpd: 75,
  },
  {
    id: 'DOM-MEM-008',
    name: '80 GPD RO Membrane - Dow Filmtec Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Dow Filmtec',
    price: 2300,
    description: 'Premium Dow Filmtec 80 GPD membrane for superior water quality.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'Genuine Dow Product, 99% Rejection, Trusted Performance',
    gpd: 80,
  },
  {
    id: 'DOM-MEM-009',
    name: '100 GPD RO Membrane - Dow Filmtec Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Dow Filmtec',
    price: 2500,
    description: 'Premium Dow Filmtec 100 GPD high-flow membrane.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'Genuine Dow Product, 99% Rejection, High-Flow',
    gpd: 100,
  },
  {
    id: 'DOM-MEM-010',
    name: '75 GPD RO Membrane - CSM Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'CSM',
    price: 1300,
    description: 'Reliable 75 GPD RO membrane from CSM, offering great value and performance.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '75 GPD, High Rejection, Cost-Effective',
    gpd: 75,
  },
  {
    id: 'DOM-MEM-011',
    name: '80 GPD RO Membrane - CSM Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'CSM',
    price: 1400,
    description: 'Reliable 80 GPD RO membrane from CSM, offering great value and performance.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '80 GPD, High Rejection, Cost-Effective',
    gpd: 80,
  },
  {
    id: 'DOM-MEM-012',
    name: '100 GPD RO Membrane - CSM Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'CSM',
    price: 1550,
    description: 'Reliable 100 GPD high-flow RO membrane from CSM.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '100 GPD, High Rejection, High-Flow',
    gpd: 100,
  },
  {
    id: 'DOM-MEM-013',
    name: '75 GPD RO Membrane - Lexpure Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Lexpure',
    price: 1200,
    description: 'Lexpure 75 GPD RO membrane, a popular choice for domestic water purifiers.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '75 GPD, Consistent Performance, Trusted Brand',
    gpd: 75,
  },
  {
    id: 'DOM-MEM-014',
    name: '80 GPD RO Membrane - Lexpure Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Lexpure',
    price: 1300,
    description: 'Lexpure 80 GPD RO membrane, a popular choice for domestic water purifiers.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '80 GPD, Consistent Performance, Trusted Brand',
    gpd: 80,
  },
  {
    id: 'DOM-MEM-015',
    name: '100 GPD RO Membrane - Lexpure Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Lexpure',
    price: 1450,
    description: 'Lexpure 100 GPD high-flow RO membrane.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '100 GPD, Consistent Performance, High-Flow',
    gpd: 100,
  },
  {
    id: 'DOM-MEM-016',
    name: '150 GPD RO Membrane - Domestic',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 1800,
    description: 'Very high-flow 150 GPD membrane for large families or light commercial use.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '150 GPD, Ultra High-Flow, Fits Standard Housing',
    gpd: 150,
  },
  {
    id: 'DOM-MEM-017',
    name: 'High TDS RO Membrane - 80 GPD',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 1600,
    description: 'Specialty membrane designed for areas with very high input water TDS levels (up to 3000 ppm).',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'For High TDS Water, 80 GPD, Enhanced Durability',
    gpd: 80,
  },
  {
    id: 'DOM-MEM-018',
    name: 'High TDS RO Membrane - 100 GPD',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 1800,
    description: 'High-flow specialty membrane designed for areas with very high input water TDS levels (up to 3000 ppm).',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'For High TDS Water, 100 GPD, Enhanced Durability',
    gpd: 100,
  },
  {
    id: 'DOM-MEM-019',
    name: 'Low Pressure RO Membrane - 80 GPD',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 1500,
    description: 'Operates efficiently at lower input water pressures, ideal for homes without a booster pump.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'Low Pressure Operation, 80 GPD, Energy Saving',
    gpd: 80,
  },
  {
    id: 'DOM-MEM-020',
    name: 'Low Pressure RO Membrane - 100 GPD',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 1700,
    description: 'High-flow membrane that operates efficiently at lower input water pressures.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'Low Pressure Operation, 100 GPD, Energy Saving',
    gpd: 100,
  },
  {
    id: 'DOM-MEM-021',
    name: 'NF (Nano-Filtration) Membrane - NF40',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 1900,
    description: 'Nano-Filtration membrane (NF40) that removes hardness while retaining essential minerals.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'Reduces Hardness, Retains Minerals, Lowers TDS Moderately',
  },
  {
    id: 'DOM-MEM-022',
    name: 'NF (Nano-Filtration) Membrane - NF80',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 2200,
    description: 'Nano-Filtration membrane (NF80) with higher rejection, acting as a softener.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'High Hardness Removal, Retains some Minerals, Softens Water',
  },
  {
    id: 'DOM-MEM-023',
    name: '125 GPD RO Membrane - Domestic',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Generic',
    price: 1700,
    description: 'High flow 125 GPD membrane for domestic systems requiring faster purification.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '125 GPD, High-Flow, Fits Standard Housing',
    gpd: 125,
  },
  {
    id: 'DOM-MEM-024',
    name: '75 GPD RO Membrane - Hi-Tech Brand',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Hi-Tech',
    price: 1250,
    description: 'Hi-Tech 75 GPD RO membrane for reliable water purification.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '75 GPD, Reliable Performance, Quality Assured',
    gpd: 75,
  },

  // A2. Domestic Pre-Filter Cartridges (Spun/Wound)
  {
    id: 'DOM-SPUN-001',
    name: '10" Spun Filter - 5 Micron, 100g',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pre-Filters / Sediment',
    brand: 'Generic',
    price: 120,
    description: 'Standard 10-inch, 5-micron spun filter (100g). Removes sand, silt, and rust.',
    image: 'https://images.unsplash.com/photo-1558191052-e39a46a5b651?q=80&w=2070&auto=format&fit=crop',
    features: '5 Micron, 100g Weight, High Dirt Holding Capacity',
  },
  {
    id: 'DOM-SPUN-002',
    name: '10" Spun Filter - 1 Micron, 100g',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pre-Filters / Sediment',
    brand: 'Generic',
    price: 130,
    description: 'Finer 1-micron 10-inch spun filter for superior sediment removal.',
    image: 'https://images.unsplash.com/photo-1558191052-e39a46a5b651?q=80&w=2070&auto=format&fit=crop',
    features: '1 Micron, 100g Weight, Finer Filtration',
  },
  {
    id: 'DOM-SPUN-003',
    name: '10" Spun Filter - 5 Micron, 110g (Premium)',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pre-Filters / Sediment',
    brand: 'Generic',
    price: 150,
    description: 'Premium quality 10-inch, 5-micron spun filter with 110g weight for longer life.',
    image: 'https://images.unsplash.com/photo-1558191052-e39a46a5b651?q=80&w=2070&auto=format&fit=crop',
    features: '5 Micron, 110g Weight, Longer Lasting',
  },
  {
    id: 'DOM-SPUN-004',
    name: '10" PP Wound Filter - 5 Micron',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pre-Filters / Sediment',
    brand: 'Generic',
    price: 180,
    description: 'Polypropylene wound filter cartridge (5 micron) for high flow rate and dirt holding capacity.',
    image: 'https://images.unsplash.com/photo-1558191052-e39a46a5b651?q=80&w=2070&auto=format&fit=crop',
    features: '5 Micron, Wound Type, High Flow Rate',
  },
  {
    id: 'DOM-SPUN-005',
    name: '20" Spun Filter - 5 Micron (Slim)',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pre-Filters / Sediment',
    brand: 'Generic',
    price: 300,
    description: '20-inch slim spun filter (5 micron) for larger domestic or commercial pre-filtration units.',
    image: 'https://images.unsplash.com/photo-1558191052-e39a46a5b651?q=80&w=2070&auto=format&fit=crop',
    features: '20-inch Slim, 5 Micron, For Commercial Pre-filtration',
  },

  // A3. Domestic Inline Filters
  {
    id: 'DOM-INLINE-001',
    name: '10" Inline Sediment Filter - Push Fit',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Inline Filters',
    brand: 'Generic',
    price: 250,
    description: '10-inch inline sediment filter with 1/4" push-fit connectors for easy installation.',
    image: 'https://images.unsplash.com/photo-1617963833936-84d720b6c09a?q=80&w=1974&auto=format&fit=crop',
    features: 'Inline Sediment, Push-Fit, Easy Installation',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-INLINE-002',
    name: '10" Inline Pre-Carbon Filter (GAC) - Push Fit',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Inline Filters',
    brand: 'Generic',
    price: 300,
    description: 'Granular Activated Carbon (GAC) inline filter to remove chlorine, taste, and odor. Push-fit connectors.',
    image: 'https://images.unsplash.com/photo-1617963833936-84d720b6c09a?q=80&w=1974&auto=format&fit=crop',
    features: 'GAC, Removes Chlorine, Improves Taste, Push-Fit',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-INLINE-003',
    name: '10" Inline Post-Carbon Filter - Push Fit',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Inline Filters',
    brand: 'Generic',
    price: 300,
    description: 'Inline post-carbon filter to enhance the taste of purified water just before it is dispensed. Push-fit.',
    image: 'https://images.unsplash.com/photo-1617963833936-84d720b6c09a?q=80&w=1974&auto=format&fit=crop',
    features: 'Taste Enhancer, Polishes Water, Push-Fit',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-INLINE-004',
    name: 'Inline Mineral Cartridge - Standard',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Inline Filters',
    brand: 'Generic',
    price: 450,
    description: 'Adds essential minerals like calcium and magnesium back into RO water, balancing pH.',
    image: 'https://images.unsplash.com/photo-1620912184852-c6776b43a789?q=80&w=2070&auto=format&fit=crop',
    features: 'Adds Healthy Minerals, Balances pH, Improves Taste',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-INLINE-005',
    name: 'Inline Alkaline Filter - Standard',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Inline Filters',
    brand: 'Generic',
    price: 600,
    description: 'Increases the pH of RO water to make it alkaline and adds antioxidant properties.',
    image: 'https://images.unsplash.com/photo-1620912184852-c6776b43a789?q=80&w=2070&auto=format&fit=crop',
    features: 'Increases pH, Antioxidant Properties, Enhances Water',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-INLINE-006',
    name: 'Inline Alkaline + Copper Filter',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Inline Filters',
    brand: 'Generic',
    price: 850,
    description: 'A combination filter that makes water alkaline and enriches it with the benefits of copper.',
    image: 'https://images.unsplash.com/photo-1620912184852-c6776b43a789?q=80&w=2070&auto=format&fit=crop',
    features: 'Alkaline + Copper, Dual Benefits, Improves Health',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-INLINE-007',
    name: 'Inline UF (Ultra-Filtration) Membrane - Push Fit',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Inline Filters',
    brand: 'Generic',
    price: 400,
    description: 'Inline Ultra-Filtration membrane to remove bacteria and viruses without electricity.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'Removes Bacteria & Viruses, Retains Minerals, Push-Fit',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-INLINE-008',
    name: 'Inline Filter Set (Sediment, Pre-Carbon, Post-Carbon)',
    mainCategory: 'Service Kits & Combo Packs',
    subcategory: 'Filter Combo Packs',
    brand: 'Generic',
    price: 800,
    description: 'A complete set of three essential inline filters for annual or bi-annual service. Push-fit.',
    image: 'https://images.unsplash.com/photo-1629849247657-611a8d1633f7?q=80&w=2070&auto=format=fit&crop',
    features: 'Complete Set, Push-Fit, Cost-Effective',
    inletOutletSize: '1/4"',
  },

  // A4. Commercial Filters & Membranes
  {
    id: 'COM-MEM-001',
    name: 'Industrial RO Membrane - 4040 Brackish Water (BW)',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Commercial RO Membranes',
    brand: 'Generic',
    price: 8500,
    description: 'High-performance 4040 size industrial RO membrane for commercial plants.',
    image: 'https://images.unsplash.com/photo-1614941408332-1b15b573d3a6d?q=80&w=2070&auto=format&fit=crop',
    features: '2400 GPD Capacity, High Salt Rejection, For Brackish Water',
    gpd: 2400,
  },
  {
    id: 'COM-MEM-002',
    name: 'Industrial RO Membrane - 8040 Brackish Water (BW)',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Commercial RO Membranes',
    brand: 'Generic',
    price: 22000,
    description: 'High-capacity 8040 size industrial RO membrane for large-scale plants.',
    image: 'https://images.unsplash.com/photo-1614941408332-1b15b573d3a6d?q=80&w=2070&auto=format&fit=crop',
    features: '10000 GPD Capacity, High Salt Rejection, For Large Plants',
    gpd: 10000,
  },
  {
    id: 'COM-MEM-003',
    name: 'Industrial RO Membrane - 4040 Dow Filmtec',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Commercial RO Membranes',
    brand: 'Dow Filmtec',
    price: 11000,
    description: 'Genuine Dow Filmtec 4040 BW membrane for unmatched performance.',
    image: 'https://images.unsplash.com/photo-1614941408332-1b15b573d3a6d?q=80&w=2070&auto=format&fit=crop',
    features: 'Genuine Dow, 2400 GPD, Superior Quality',
    gpd: 2400,
  },
  {
    id: 'COM-MEM-004',
    name: 'Industrial RO Membrane - 4040 Hydranautics',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Commercial RO Membranes',
    brand: 'Hydranautics',
    price: 10500,
    description: 'Hydranautics CPA series 4040 membrane, known for high rejection rates.',
    image: 'https://images.unsplash.com/photo-1614941408332-1b15b573d3a6d?q=80&w=2070&auto=format&fit=crop',
    features: 'Hydranautics CPA, 2500 GPD, High Rejection',
    gpd: 2500,
  },
  {
    id: 'COM-FILTER-001',
    name: '20" Jumbo Spun Filter - 5 Micron',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Big Blue Filters',
    brand: 'Generic',
    price: 700,
    description: '20-inch jumbo spun filter cartridge (5 micron) for commercial pre-filter housings.',
    image: 'https://images.unsplash.com/photo-1558191052-e39a46a5b651?q=80&w=2070&auto=format&fit=crop',
    features: '20-inch Jumbo, 5 Micron, High Capacity',
  },
  {
    id: 'COM-FILTER-002',
    name: '20" Jumbo CTO (Carbon Block) Filter',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Big Blue Filters',
    brand: 'Generic',
    price: 2500,
    description: '20-inch jumbo carbon block filter for effective chlorine and chemical removal in commercial systems.',
    image: 'https://images.unsplash.com/photo-1617963833936-84d720b6c09a?q=80&w=1974&auto=format&fit=crop',
    features: '20-inch Jumbo, Carbon Block, High Chlorine Removal',
  },
  {
    id: 'COM-FILTER-003',
    name: 'SS Bag Filter Housing - 4"x20"',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'SS Housings',
    brand: 'Generic',
    price: 8000,
    description: 'Stainless Steel bag filter housing (4"x20") for high-flow sediment filtration.',
    image: 'https://images.unsplash.com/photo-1541701494587-b959e7825776?q=80&w=2070&auto=format&fit=crop',
    features: 'SS 304, High Flow Rate, Durable',
    material: 'Stainless Steel',
  },
  {
    id: 'COM-FILTER-004',
    name: 'SS Micron Cartridge Filter Housing - 3 Round, 20"',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'SS Housings',
    brand: 'Generic',
    price: 15000,
    description: 'Stainless Steel housing for 3 cartridges of 20" length. For fine filtration.',
    image: 'https://images.unsplash.com/photo-1541701494587-b959e7825776?q=80&w=2070&auto=format&fit=crop',
    features: 'SS 304, Holds 3 Cartridges, High Pressure',
    material: 'Stainless Steel',
  },
  {
    id: 'COM-CHEM-001',
    name: 'Antiscalant Chemical (5Ltr Can)',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Chemicals',
    brand: 'Generic',
    price: 1800,
    description: 'High-performance antiscalant chemical to prevent scaling on commercial RO membranes.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'Prevents Scaling, Improves Membrane Life, 5 Litre Pack',
  },
  {
    id: 'COM-RESIN-001',
    name: 'Water Softener Resin - Cation (25Ltr Bag)',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Chemicals',
    brand: 'Generic',
    price: 3500,
    description: 'High-quality cation resin for water softeners used in commercial RO pre-treatment.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'High Exchange Capacity, For Water Softeners, 25 Litre Bag',
  },

  // B1. Domestic Pumps & Spares
  {
    id: 'DOM-PUMP-001',
    name: 'Booster Pump 100 GPD - 24V',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pump (Booster Pump)',
    brand: 'Generic',
    price: 2200,
    description: 'Standard 100 GPD, 24V booster pump to increase water pressure for optimal membrane performance.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: '100 GPD, 24V, Low Noise, High Efficiency',
    gpd: 100,
    voltage: '24V',
  },
  {
    id: 'DOM-PUMP-002',
    name: 'Booster Pump 100 GPD - 36V',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pump (Booster Pump)',
    brand: 'Generic',
    price: 2500,
    description: 'High-pressure 100 GPD, 36V booster pump for improved performance and purification.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: '100 GPD, 36V, High Pressure, For 36V SMPS',
    gpd: 100,
    voltage: '36V',
  },
  {
    id: 'DOM-PUMP-003',
    name: 'Brand: Echen Pump - 100 GPD',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pump (Booster Pump)',
    brand: 'Echen',
    price: 2800,
    description: 'Genuine Echen 100 GPD booster pump, known for its quality and long life.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: '100 GPD, 24V, Genuine Echen, Reliable',
    gpd: 100,
    voltage: '24V',
  },
  {
    id: 'DOM-PUMP-004',
    name: 'Brand: Grand Forest (GF) Pump - 100 GPD',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pump (Booster Pump)',
    brand: 'Grand Forest',
    price: 2700,
    description: 'Grand Forest (GF) 100 GPD booster pump, a trusted name in the industry.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: '100 GPD, 24V, Grand Forest Brand, Durable',
    gpd: 100,
    voltage: '24V',
  },
  {
    id: 'DOM-PUMP-005',
    name: 'Pump Head - 100 GPD',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pump (Booster Pump)',
    brand: 'Generic',
    price: 800,
    description: 'Replacement head for 100 GPD domestic RO booster pumps.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: 'Replacement Part, For 100 GPD Pumps, Easy to Fit',
  },

  // B2. Domestic Electrical Parts
  {
    id: 'DOM-ELEC-001',
    name: 'SMPS Power Supply - 24V, 2.5A',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'SMPS / Adapter',
    brand: 'Generic',
    price: 600,
    description: 'Reliable 24V 2.5A SMPS power supply for domestic RO systems.',
    image: 'https://images.unsplash.com/photo-1563209995-884561a02127?q=80&w=2070&auto=format&fit=crop',
    features: '24V 2.5A, Stable Output, Overload Protection',
    voltage: '24V',
  },
  {
    id: 'DOM-ELEC-002',
    name: 'Solenoid Valve (SV) - 24V DC, Push Fit',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Solenoid Valve',
    brand: 'Generic',
    price: 350,
    description: '24V DC solenoid valve with push-fit connectors. Acts as an automatic water inlet controller.',
    image: 'https://images.unsplash.com/photo-1619864275553-913745a49f87?q=80&w=2070&auto=format&fit=crop',
    features: '24V, Push-Fit, Prevents Water Wastage',
    voltage: '24V',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-ELEC-003',
    name: 'Low-Pressure Switch (LPS) - Push Fit',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Low & High Pressure Switches',
    brand: 'Generic',
    price: 150,
    description: 'Protects the RO pump from running dry by shutting it off if inlet pressure is too low.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop',
    features: 'Protects Pump, Automatic Cut-off, Push-Fit',
  },
  {
    id: 'DOM-ELEC-004',
    name: 'High-Pressure Switch (HPS) - Push Fit',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Low & High Pressure Switches',
    brand: 'Generic',
    price: 150,
    description: 'Shuts off the RO pump when the storage tank is full, saving electricity and water.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop',
    features: 'Tank Full Cut-off, Automatic Operation, Push-Fit',
  },
  {
    id: 'DOM-ELEC-005',
    name: 'Float Switch - Mechanical, Top Fitting',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Float Valves',
    brand: 'Generic',
    price: 200,
    description: 'Mechanical float switch to control the water level inside the storage tank.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop',
    features: 'Mechanical, Controls Water Level, Reliable',
  },
  {
    id: 'DOM-ELEC-006',
    name: 'UV Choke (Ballast) - Electronic, 11W',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'UV Spares',
    brand: 'Generic',
    price: 450,
    description: 'Electronic ballast (choke) for 11W UV lamps used in RO+UV systems.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop',
    features: 'For 11W UV Lamp, Electronic, Stable Power',
  },
  {
    id: 'DOM-ELEC-007',
    name: 'UV Lamp - 11W, 8-inch',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'UV Spares',
    brand: 'Generic',
    price: 350,
    description: 'Replacement 11W UV lamp for disinfection in RO+UV water purifiers.',
    image: 'https://images.unsplash.com/photo-1589283733355-c802693a7469?q=80&w=2014&auto=format&fit=crop',
    features: '11W Power, Kills Bacteria & Viruses, 8-inch length',
  },
  {
    id: 'DOM-ELEC-008',
    name: 'UV Quartz Glass Sleeve for 11W Lamp',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'UV Spares',
    brand: 'Generic',
    price: 300,
    description: 'Protective quartz glass sleeve/tube for 11W UV lamps.',
    image: 'https://images.unsplash.com/photo-1589283733355-c802693a7469?q=80&w=2014&auto=format&fit=crop',
    features: 'Protects UV Lamp, High Transparency, Durable',
  },

  // B3. Commercial Pumps & Electrical
  {
    id: 'COM-PUMP-001',
    name: 'High-Pressure Pump - 250 LPH',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'High-Pressure Pumps',
    brand: 'Generic',
    price: 15000,
    description: 'Rotary vane high-pressure pump suitable for 250 LPH commercial RO plants.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: '250 LPH, High Pressure, Continuous Duty',
  },
  {
    id: 'COM-PUMP-002',
    name: 'Vertical Multistage Pump - 1 HP',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'High-Pressure Pumps',
    brand: 'Generic',
    price: 25000,
    description: '1 HP vertical multistage high-pressure pump for 500-1000 LPH RO plants.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: '1 HP, Vertical, Stainless Steel, High Head',
  },
  {
    id: 'COM-PUMP-003',
    name: 'Brand: CNP Pump - 1 HP',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'High-Pressure Pumps',
    brand: 'CNP',
    price: 32000,
    description: 'Genuine CNP 1 HP vertical multistage pump, a leading brand in commercial pumps.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: '1 HP, Genuine CNP, Reliable Performance',
  },
  {
    id: 'COM-PUMP-004',
    name: 'Raw Water Feed Pump - 1 HP Monoblock',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Raw Water Pump',
    brand: 'Generic',
    price: 7000,
    description: '1 HP monoblock centrifugal pump for feeding raw water to the RO plant.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: '1 HP, Monoblock, High Suction',
  },
  {
    id: 'COM-PUMP-005',
    name: 'Dosing Pump - Antiscalant',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Dosing Pumps',
    brand: 'Generic',
    price: 6500,
    description: 'Electronic dosing pump for accurately injecting antiscalant chemical to protect membranes.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: 'Adjustable Dose, Chemical Resistant, Precise',
  },
  {
    id: 'COM-ELEC-001',
    name: 'RO Control Panel - 250 LPH, Relay Based',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Control Panels',
    brand: 'Generic',
    price: 8500,
    description: 'Automatic relay-based control panel for 250 LPH RO plants. Manages all operations.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop',
    features: 'Automated Logic, Overload Protection, Easy to Operate',
  },
  {
    id: 'COM-ELEC-002',
    name: 'Pressure Gauge - 0-21 kg/cm², Panel Mount, Liquid Filled',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Pressure Gauges',
    brand: 'Generic',
    price: 700,
    description: 'Liquid (glycerin) filled pressure gauge for stable high-pressure readings. 0-21 kg/cm² (approx 300 PSI).',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop',
    features: 'Liquid Filled, Stable Reading, Panel Mount, 0-21 kg/cm²',
  },
  {
    id: 'COM-ELEC-003',
    name: 'Rotameter (Flow Meter) - 0-600 LPH',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Rotameter / Flow Meter',
    brand: 'Generic',
    price: 1800,
    description: 'Panel-mounted rotameter to measure product and reject water flow rates up to 600 LPH.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop',
    features: '0-600 LPH Range, Panel Mounted, Acrylic Body',
  },
  {
    id: 'COM-ELEC-004',
    name: 'Online TDS/Conductivity Meter',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Conductivity/TDS Controller',
    brand: 'Generic',
    price: 4500,
    description: 'Panel-mounted digital TDS meter for continuous monitoring of product water quality.',
    image: 'https://images.unsplash.com/photo-1628149849209-968568b65553?q=80&w=2070&auto=format&fit=crop',
    features: 'Continuous Monitoring, Digital Display, Panel Mount',
  },
  {
    id: 'COM-ELEC-005',
    name: 'Commercial UV System - 1000 LPH',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'UV Systems',
    brand: 'Generic',
    price: 12000,
    description: 'High-capacity UV sterilization system for 1000 LPH flow rate. Stainless steel chamber.',
    image: 'https://images.unsplash.com/photo-1589283733355-c802693a7469?q=80&w=2014&auto=format&fit=crop',
    features: '1000 LPH, SS 304 Chamber, Kills 99.9% Microbes',
  },
  {
    id: 'COM-ELEC-006',
    name: 'SS Skid/Frame - 250 LPH',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'SS Skids / RO Frames',
    brand: 'Generic',
    price: 12000,
    description: 'Stainless steel skid/frame for assembling a 250 LPH commercial RO plant.',
    image: 'https://images.unsplash.com/photo-1631049352163-3e21a8d1033b?q=80&w=1974&auto=format&fit=crop',
    features: 'SS 304, Compact Design, Pre-Drilled Mounts',
    material: 'Stainless Steel',
  },

  // C1. Domestic Pipe & Fittings
  {
    id: 'DOM-FIT-001',
    name: 'RO Pipe 1/4" - White (per meter)',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pipe / Tubing',
    brand: 'Generic',
    price: 25,
    description: 'Food-grade 1/4 inch RO pipe in white color. Sold per meter.',
    image: 'https://images.unsplash.com/photo-1596463284487-32898f060783?q=80&w=1954&auto=format&fit=crop',
    features: '1/4" Size, Food-Grade, White',
    inletOutletSize: '1/4"',
    color: 'White',
  },
  {
    id: 'DOM-FIT-002',
    name: 'Elbow 1/4" x 1/4"',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Fittings / Connectors',
    brand: 'Generic',
    price: 30,
    description: 'Push-fit elbow connector for 1/4" RO pipe.',
    image: 'https://images.unsplash.com/photo-1543292489-0f475739c316?q=80&w=2070&auto=format&fit=crop',
    features: 'Push-Fit, 1/4" x 1/4", Leak-Proof',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-FIT-003',
    name: 'Tee 1/4" x 1/4" x 1/4"',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Fittings / Connectors',
    brand: 'Generic',
    price: 40,
    description: 'Push-fit tee connector to split a 1/4" line.',
    image: 'https://images.unsplash.com/photo-1543292489-0f475739c316?q=80&w=2070&auto=format&fit=crop',
    features: 'Push-Fit, 1/4" Tee, Durable Plastic',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-FIT-004',
    name: 'Ball Valve 1/4"',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Fittings / Connectors',
    brand: 'Generic',
    price: 100,
    description: 'Inline ball valve with 1/4" push-fit connectors to control water flow.',
    image: 'https://images.unsplash.com/photo-1543292489-0f475739c316?q=80&w=2070&auto=format&fit=crop',
    features: 'Push-Fit, 1/4", Manual Shut-off',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-FIT-005',
    name: 'Flow Restrictor (FR) 450',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Check Valve / NRV',
    brand: 'Generic',
    price: 80,
    description: '450ml flow restrictor to maintain pressure on the RO membrane. For 80-100 GPD membranes.',
    image: 'https://images.unsplash.com/photo-1594498822319-6187cf9a80b5?q=80&w=2070&auto=format&fit=crop',
    features: '450ml, For 80-100 GPD Membranes, Improves Recovery',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-FIT-006',
    name: 'Inlet Diverter Valve Set - 1/2" to 1/4" (Steel)',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Fittings / Connectors',
    brand: 'Generic',
    price: 350,
    description: 'Steel diverter valve set to connect RO inlet pipe to a standard 1/2" tap line.',
    image: 'https://images.unsplash.com/photo-1543292489-0f475739c316?q=80&w=2070&auto=format&fit=crop',
    features: 'Steel, 1/2" to 1/4", Durable',
    material: 'Steel',
  },

  // C2. Housings, Cabinets & Tanks
  {
    id: 'DOM-HOUSE-001',
    name: '10" Pre-Filter Housing - White Bowl, Double O-Ring',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Filter Housing',
    brand: 'Generic',
    price: 450,
    description: 'High-quality 10-inch pre-filter housing with double O-rings for a leak-proof seal.',
    image: 'https://images.unsplash.com/photo-1541701494587-b959e7825776?q=80&w=2070&auto=format&fit=crop',
    features: 'Double O-Ring, 10-inch, Food-Grade Plastic',
  },
  {
    id: 'DOM-HOUSE-002',
    name: 'Domestic Membrane Housing - 1812, Ribbed',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Membrane Housing',
    brand: 'Generic',
    price: 400,
    description: 'Standard ribbed membrane housing for all domestic 1812 size RO membranes.',
    image: 'https://images.unsplash.com/photo-1629840282877-1718153b6f9e?q=80&w=1964&auto=format&fit=crop',
    features: 'Fits 1812 Membranes, Ribbed Design, High-Pressure Resistant',
  },
  {
    id: 'DOM-HOUSE-003',
    name: 'RO Storage Tank - 3.2 Gallon Steel',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Tank',
    brand: 'Generic',
    price: 2800,
    description: 'NSF-certified 3.2 gallon (approx. 12L) pressurized steel storage tank.',
    image: 'https://images.unsplash.com/photo-1541701494587-b959e7825776?q=80&w=2070&auto=format&fit=crop',
    features: '3.2 Gallon, Steel, NSF Certified, Pre-Pressurized',
    material: 'Steel',
  },
  {
    id: 'DOM-HOUSE-004',
    name: 'RO Cabinet - Kent Grand Type Model',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'RO Cabinet Body',
    brand: 'Generic',
    price: 2500,
    description: 'Replacement cabinet body with a design similar to Kent Grand models.',
    image: 'https://images.unsplash.com/photo-1629840282877-1718153b6f9e?q=80&w=1964&auto=format&fit=crop',
    features: 'Kent Grand Design, Food-Grade Plastic, Wall-Mountable',
  },

  // C3. Faucets, Clamps & Tools
  {
    id: 'ACC-FAUCET-001',
    name: 'RO Faucet - Long Reach, Steel',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'Taps / Faucets',
    brand: 'Generic',
    price: 750,
    description: 'Elegant long-reach stainless steel faucet for RO systems. Lead-free with ceramic valve.',
    image: 'https://images.unsplash.com/photo-1596746002334-a8220551e1e2?q=80&w=1974&auto=format&fit=crop',
    features: 'Stainless Steel, Long Reach, Ceramic Disc',
    material: 'Steel',
  },
  {
    id: 'ACC-TOOL-001',
    name: 'Pre-Filter Housing Wrench - Plastic',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'Wrenches / Tools',
    brand: 'Generic',
    price: 120,
    description: 'Durable plastic wrench for opening and tightening 10" pre-filter housings.',
    image: 'https://images.unsplash.com/photo-1558611848-ea515b5e39c4?q=80&w=2070&auto=format&fit=crop',
    features: 'For 10" Housings, Durable Plastic, Essential Tool',
  },
  {
    id: 'ACC-TOOL-002',
    name: 'RO Pipe Cutter Tool',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'Wrenches / Tools',
    brand: 'Generic',
    price: 180,
    description: 'Tool for making clean, square cuts on RO tubing for leak-free connections.',
    image: 'https://images.unsplash.com/photo-1558611848-ea515b5e39c4?q=80&w=2070&auto=format&fit=crop',
    features: 'Clean Cuts, For 1/4" & 3/8" Pipes, Easy to Use',
  },
  {
    id: 'ACC-TDS-001',
    name: 'Pocket TDS Meter - Basic',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'TDS Meters',
    brand: 'Generic',
    price: 350,
    discountPrice: 300,
    description: 'Handy digital TDS meter to check water quality and RO system performance.',
    image: 'https://images.unsplash.com/photo-1628149849209-968568b65553?q=80&w=2070&auto=format&fit=crop',
    features: 'Accurate Readings, Pocket-Sized, Auto-off Function',
  },

  // C4. Commercial Housings & Fittings
  {
    id: 'COM-HOUSE-001',
    name: '20" Jumbo Filter Housing (Big Blue) - 1" Port',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Big Blue Filter Housing',
    brand: 'Generic',
    price: 2200,
    description: '20-inch Big Blue housing for commercial pre-filters with 1-inch inlet/outlet ports.',
    image: 'https://images.unsplash.com/photo-1541701494587-b959e7825776?q=80&w=2070&auto=format&fit=crop',
    features: '20-inch Jumbo, 1" Ports, High Flow Capacity',
    inletOutletSize: '1"',
  },
  {
    id: 'COM-HOUSE-002',
    name: 'FRP Pressure Vessel - 4040, 300 PSI',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Pressure Vessels (FRP)',
    brand: 'Generic',
    price: 11000,
    description: 'Durable FRP pressure vessel for a single 4040 commercial RO membrane. 300 PSI rating.',
    image: 'https://images.unsplash.com/photo-1596791882046-e575d5f99992?q=80&w=2070&auto=format&fit=crop',
    features: 'For 4040 Membrane, 300 PSI, Corrosion Resistant',
    material: 'FRP',
  },
  {
    id: 'COM-HOUSE-003',
    name: 'SS 304 Membrane Housing - 4040, End Port',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'SS Housings',
    brand: 'Generic',
    price: 9000,
    description: 'Seamless stainless steel (SS 304) membrane housing for 4040 membranes.',
    image: 'https://images.unsplash.com/photo-1596791882046-e575d5f99992?q=80&w=2070&auto=format&fit=crop',
    features: 'SS 304, Seamless, End Port, High Pressure',
    material: 'Stainless Steel',
  },

  // D. Kits, Combos & Complete Systems
  {
    id: 'KIT-SVC-001',
    name: 'Annual Service Kit (3 Spun, 1 Sediment, 1 Carbon, 1 Post-Carbon)',
    mainCategory: 'Service Kits & Combo Packs',
    subcategory: 'Annual Maintenance Kits',
    brand: 'Generic',
    price: 1200,
    discountPrice: 999,
    description: 'A complete one-year filter service kit for standard domestic RO systems.',
    image: 'https://images.unsplash.com/photo-1629849247657-611a8d1633f7?q=80&w=2070&auto=format=fit&crop',
    features: 'Full Year Supply, All Pre-filters Included, Cost-Effective',
  },
  {
    id: 'KIT-SVC-002',
    name: 'Full Service Kit (Annual Kit + 80 GPD Membrane)',
    mainCategory: 'Service Kits & Combo Packs',
    subcategory: 'Annual Maintenance Kits',
    brand: 'Generic',
    price: 2000,
    description: 'A complete service kit including all filters and an 80 GPD RO membrane.',
    image: 'https://images.unsplash.com/photo-1629849247657-611a8d1633f7?q=80&w=2070&auto=format=fit&crop',
    features: 'Complete Service, Includes Membrane, Great Value',
  },
  {
    id: 'KIT-SVC-003',
    name: 'Brand-Specific Compatible Filter Kit (for Kent Grand)',
    mainCategory: 'Service Kits & Combo Packs',
    subcategory: 'Brand-Specific Kits',
    brand: 'Kent',
    price: 1500,
    description: 'A filter kit with parts compatible with Kent Grand and similar models.',
    image: 'https://images.unsplash.com/photo-1629849247657-611a8d1633f7?q=80&w=2070&auto=format=fit&crop',
    features: 'For Kent Models, High-Quality Spares, Easy Replacement',
  },
  {
    id: 'KIT-SVC-004',
    name: 'Installation Kit (Pipe, Inlet Valve, Drain Clamp, Wrench, Teflon)',
    mainCategory: 'Service Kits & Combo Packs',
    subcategory: 'Startup Installation Kits',
    brand: 'Generic',
    price: 650,
    description: 'Everything you need for a new RO installation or re-installation.',
    image: 'https://images.unsplash.com/photo-1558611848-ea515b5e39c4?q=80&w=2070&auto=format&fit=crop',
    features: 'Complete Installation Set, High-Quality Components, Saves Time',
  },
  {
    id: 'SYS-DOM-001',
    name: 'Complete Domestic RO System - RO+UV+UF+TDS Adjuster',
    mainCategory: 'Complete RO Systems',
    subcategory: 'Domestic RO Systems',
    brand: 'Generic',
    price: 12000,
    discountPrice: 9999,
    description: 'A complete 7-stage RO+UV+UF+TDS Adjuster water purifier.',
    image: 'https://images.unsplash.com/photo-1629840282877-1718153b6f9e?q=80&w=1964&auto=format&fit=crop',
    features: 'Multi-Stage Purification, Includes UV & UF, Wall-Mountable',
  },
  {
    id: 'SYS-COM-001',
    name: 'Complete Commercial RO Plant - 250 LPH',
    mainCategory: 'Complete RO Systems',
    subcategory: 'Commercial RO Plants',
    brand: 'Generic',
    price: 75000,
    description: 'A complete 250 Liters Per Hour commercial RO plant, mounted on a stainless steel skid.',
    image: 'https://images.unsplash.com/photo-1631049352163-3e21a8d1033b?q=80&w=1974&auto=format&fit=crop',
    features: '250 LPH, SS Skid Mounted, Fully Automatic, High Recovery',
  },
  {
    id: 'SYS-COM-002',
    name: 'Complete Commercial RO Plant - 500 LPH',
    mainCategory: 'Complete RO Systems',
    subcategory: 'Commercial RO Plants',
    brand: 'Generic',
    price: 125000,
    description: 'A complete 500 Liters Per Hour commercial RO plant, mounted on a stainless steel skid.',
    image: 'https://images.unsplash.com/photo-1631049352163-3e21a8d1033b?q=80&w=1974&auto=format&fit=crop',
    features: '500 LPH, SS Skid Mounted, Fully Automatic, For Medium Scale Use',
  },
];
