
import type { Part } from './types';

export const partsData: Part[] = [
  // 1. Domestic RO Parts
  {
    id: 'DOM-MEM-001',
    name: 'Vontron 80 GPD RO Membrane',
    name_hi: 'वॉन्ट्रॉन 80 GPD आरओ मेम्ब्रेन',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Vontron',
    price: 1800,
    discountPrice: 1650,
    description: 'High-performance 80 GPD RO membrane from Vontron, offering excellent salt rejection and long-lasting durability for pure drinking water.',
    description_hi: 'वॉन्ट्रॉन की उच्च-प्रदर्शन वाली 80 GPD आरओ मेम्ब्रेन, जो शुद्ध पीने के पानी के लिए उत्कृष्ट नमक अस्वीकृति और लंबे समय तक चलने वाली ड्यूरेबिलिटी प्रदान करती है।',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: '98% Salt Rejection, High Flow Rate, Fits Standard Housings',
    features_hi: '98% नमक अस्वीकृति, उच्च प्रवाह दर, मानक हाउसिंग में फिट बैठता है',
    gpd: 80,
    material: 'Polyamide Thin-Film Composite',
  },
  {
    id: 'DOM-FILTER-001',
    name: '5 Micron Spun Filter',
    name_hi: '5 माइक्रोन स्पन फ़िल्टर',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pre-Filters / Sediment',
    brand: 'Generic',
    price: 150,
    description: '10-inch spun polypropylene sediment filter. Removes sand, silt, dirt, and rust particles down to 5 microns.',
    description_hi: '10-इंच स्पन पॉलीप्रोपाइलीन सेडिमेंट फ़िल्टर। 5 माइक्रोन तक रेत, गाद, गंदगी और जंग के कणों को हटाता है।',
    image: 'https://images.unsplash.com/photo-1558191052-e39a46a5b651?q=80&w=2070&auto=format&fit=crop',
    features: 'High Dirt Holding Capacity, Universal Fit, Graded Density',
    features_hi: 'उच्च गंदगी धारण क्षमता, यूनिवर्सल फिट, ग्रेडेड घनत्व',
    inletOutletSize: 'N/A',
  },
  {
    id: 'DOM-FILTER-002',
    name: 'Inline Carbon Filter (CTO)',
    name_hi: 'इनलाइन कार्बन फ़िल्टर (CTO)',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Carbon Filters',
    brand: 'AquaPure',
    price: 450,
    description: 'Inline activated carbon block filter for removing chlorine, bad taste, and odors, improving the overall quality of your water.',
    description_hi: 'क्लोरीन, खराब स्वाद और गंध को हटाने के लिए इनलाइन सक्रिय कार्बन ब्लॉक फ़िल्टर, आपके पानी की समग्र गुणवत्ता में सुधार करता है।',
    image: 'https://images.unsplash.com/photo-1617963833936-84d720b6c09a?q=80&w=1974&auto=format&fit=crop',
    features: 'Coconut Shell Carbon, Reduces Chlorine, Improves Taste',
    features_hi: 'नारियल शेल कार्बन, क्लोरीन कम करता है, स्वाद में सुधार करता है',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-FILTER-003',
    name: 'Mineral Cartridge',
    name_hi: 'मिनरल कार्ट्रिज',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Post Carbon / Taste Enhancers',
    brand: 'EcoWater',
    price: 500,
    description: 'Adds essential minerals like calcium and magnesium back into RO purified water, balances pH and enhances taste.',
    description_hi: 'आरओ शुद्ध पानी में कैल्शियम और मैग्नीशियम जैसे आवश्यक खनिजों को वापस जोड़ता है, पीएच को संतुलित करता है और स्वाद बढ़ाता है।',
    image: 'https://images.unsplash.com/photo-1620912184852-c6776b43a789?q=80&w=2070&auto=format&fit=crop',
    features: 'Adds healthy minerals, Balances pH, Improves Water Taste',
    features_hi: 'स्वस्थ खनिज जोड़ता है, पीएच संतुलित करता है, पानी का स्वाद सुधारता है',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-PUMP-001',
    name: '100 GPD Booster Pump',
    name_hi: '100 GPD बूस्टर पंप',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pump (Booster Pump)',
    brand: 'PureStream',
    price: 2500,
    description: 'A powerful and quiet 100 GPD booster pump to increase water pressure for optimal RO membrane performance.',
    description_hi: 'इष्टतम आरओ मेम्ब्रेन प्रदर्शन के लिए पानी का दबाव बढ़ाने के लिए एक शक्तिशाली और शांत 100 GPD बूस्टर पंप।',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: 'Low Noise, High Efficiency, Long Life',
    features_hi: 'कम शोर, उच्च दक्षता, लंबा जीवन',
    gpd: 100,
    voltage: '24V',
  },
  {
    id: 'DOM-VALVE-001',
    name: 'RO Solenoid Valve (SV)',
    name_hi: 'आरओ सोलनॉइड वाल्व (SV)',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Solenoid Valve',
    brand: 'HydroFlow',
    price: 350,
    description: '24V DC solenoid valve that acts as an automatic water inlet controller, preventing water wastage.',
    description_hi: '24V DC सोलनॉइड वाल्व जो एक स्वचालित जल इनलेट नियंत्रक के रूप में कार्य करता है, पानी की बर्बादी को रोकता है।',
    image: 'https://images.unsplash.com/photo-1619864275553-913745a49f87?q=80&w=2070&auto=format&fit=crop',
    features: 'Leak-proof, Quick Connect, Low Power Consumption',
    features_hi: 'लीक-प्रूफ, त्वरित कनेक्ट, कम बिजली की खपत',
    voltage: '24V',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-PSU-001',
    name: 'RO SMPS Adapter 2.5A',
    name_hi: 'आरओ एसएमपीएस एडॉप्टर 2.5A',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'SMPS / Adapter',
    brand: 'Generic',
    price: 600,
    description: 'Reliable 24V 2.5A SMPS power supply for RO systems. Provides stable power to the pump and other components.',
    description_hi: 'आरओ सिस्टम के लिए विश्वसनीय 24V 2.5A एसएमपीएस बिजली की आपूर्ति। पंप और अन्य घटकों को स्थिर शक्ति प्रदान करता है।',
    image: 'https://images.unsplash.com/photo-1563209995-884561a02127?q=80&w=2070&auto=format&fit=crop',
    features: 'Overload Protection, Stable Output, Compact Size',
    features_hi: 'अधिभार संरक्षण, स्थिर आउटपुट, कॉम्पैक्ट आकार',
    voltage: '24V',
  },
  {
    id: 'DOM-HOUSING-001',
    name: 'Standard Membrane Housing',
    name_hi: 'मानक मेम्ब्रेन हाउसिंग',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Membrane Housing',
    brand: 'EcoWater',
    price: 400,
    description: 'Durable white housing for standard 1812 size domestic RO membranes. Includes double O-ring for a secure, leak-proof seal.',
    description_hi: 'मानक 1812 आकार की घरेलू आरओ मेम्ब्रेन के लिए टिकाऊ सफेद हाउसिंग। सुरक्षित, लीक-प्रूफ सील के लिए डबल ओ-रिंग शामिल है।',
    image: 'https://images.unsplash.com/photo-1629840282877-1718153b6f9e?q=80&w=1964&auto=format&fit=crop',
    features: 'Double O-Ring Seal, Food-grade Plastic, High-Pressure Resistant',
    features_hi: 'डबल ओ-रिंग सील, फूड-ग्रेड प्लास्टिक, उच्च दबाव प्रतिरोधी',
    material: 'ABS',
  },
  {
    id: 'DOM-FAUCET-001',
    name: 'Steel RO Tap',
    name_hi: 'स्टील आरओ नल',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Taps / Faucets',
    brand: 'AquaPure',
    price: 750,
    description: 'Elegant and durable stainless steel faucet for RO systems. Lead-free with a smooth ceramic valve for long life.',
    description_hi: 'आरओ सिस्टम के लिए सुरुचिपूर्ण और टिकाऊ स्टेनलेस स्टील नल। लंबे जीवन के लिए एक चिकनी सिरेमिक वाल्व के साथ सीसा रहित।',
    image: 'https://images.unsplash.com/photo-1596746002334-a8220551e1e2?q=80&w=1974&auto=format&fit=crop',
    features: 'Lead-Free, Ceramic Disc, 360° Swivel',
    features_hi: 'सीसा रहित, सिरेमिक डिस्क, 360° कुंडा',
    material: 'Stainless Steel',
  },
  {
    id: 'DOM-PIPE-001',
    name: 'RO Pipe 1/4" (10m Roll)',
    name_hi: 'आरओ पाइप 1/4" (10 मीटर रोल)',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pipe / Tubing',
    brand: 'Generic',
    price: 250,
    description: '10-meter roll of food-grade 1/4 inch RO pipe. Flexible and durable for all domestic RO system connections.',
    description_hi: '10-मीटर रोल खाद्य-ग्रेड 1/4 इंच आरओ पाइप। सभी घरेलू आरओ सिस्टम कनेक्शन के लिए लचीला और टिकाऊ।',
    image: 'https://images.unsplash.com/photo-1596463284487-32898f060783?q=80&w=1954&auto=format&fit=crop',
    features: 'Food-Grade Material, Flexible, Kink-Resistant',
    features_hi: 'खाद्य-ग्रेड सामग्री, लचीला, किंक-प्रतिरोधी',
    inletOutletSize: '1/4"',
    color: 'White',
  },
  {
    id: 'DOM-FITTING-001',
    name: 'Push-Fit Elbow Connector 1/4"',
    name_hi: 'पुश-फिट एल्बो कनेक्टर 1/4"',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Fittings / Connectors',
    brand: 'HydroFlow',
    price: 30,
    description: 'Quick connect 1/4 inch elbow fitting for secure, leak-free connections in tight spaces.',
    description_hi: 'तंग स्थानों में सुरक्षित, लीक-मुक्त कनेक्शन के लिए त्वरित कनेक्ट 1/4 इंच एल्बो फिटिंग।',
    image: 'https://images.unsplash.com/photo-1543292489-0f475739c316?q=80&w=2070&auto=format&fit=crop',
    features: 'Quick Connect, Leak-Proof, Food-Grade Plastic',
    features_hi: 'त्वरित कनेक्ट, लीक-प्रूफ, फूड-ग्रेड प्लास्टिक',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-VALVE-002',
    name: 'Flow Restrictor 450ml',
    name_hi: 'फ्लो रेस्ट्रिक्टर 450ml',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Check Valve / NRV',
    brand: 'Generic',
    price: 80,
    description: '450ml flow restrictor (FR) maintains the ideal pressure ratio for the RO membrane, maximizing efficiency and lifespan.',
    description_hi: '450ml फ्लो रेस्ट्रिक्टर (FR) आरओ मेम्ब्रेन के लिए आदर्श दबाव अनुपात बनाए रखता है, दक्षता और जीवनकाल को अधिकतम करता है।',
    image: 'https://images.unsplash.com/photo-1594498822319-6187cf9a80b5?q=80&w=2070&auto=format&fit=crop',
    features: 'Improves Recovery Rate, Easy to Install, For 80-100 GPD Membranes',
    features_hi: 'रिकवरी दर में सुधार, स्थापित करने में आसान, 80-100 GPD मेम्ब्रेन के लिए',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-SWITCH-001',
    name: 'Low Pressure Switch (LPS)',
    name_hi: 'लो प्रेशर स्विच (LPS)',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Low & High Pressure Switches',
    brand: 'PureStream',
    price: 150,
    description: 'Protects the RO pump from running dry by shutting it off if the incoming water pressure is too low.',
    description_hi: 'यदि आने वाला पानी का दबाव बहुत कम है तो आरओ पंप को बंद करके उसे सूखा चलने से बचाता है।',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop',
    features: 'Protects Pump Motor, Universal Fit, Automatic Operation',
    features_hi: 'पंप मोटर की सुरक्षा करता है, यूनिवर्सल फिट, स्वचालित संचालन',
    voltage: '24V/36V',
  },
  {
    id: 'DOM-TANK-001',
    name: '3.2 Gallon RO Storage Tank',
    name_hi: '3.2 गैलन आरओ स्टोरेज टैंक',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Tank',
    brand: 'EcoWater',
    price: 2800,
    description: 'NSF-certified 3.2 gallon (approx. 12L) steel storage tank. Provides a ready supply of purified water.',
    description_hi: 'NSF-प्रमाणित 3.2 गैलन (लगभग 12L) स्टील स्टोरेज टैंक। शुद्ध पानी की तैयार आपूर्ति प्रदान करता है।',
    image: 'https://images.unsplash.com/photo-1541701494587-b959e7825776?q=80&w=2070&auto=format&fit=crop',
    features: 'Steel Construction, NSF Certified, Pre-Pressurized',
    features_hi: 'स्टील निर्माण, NSF प्रमाणित, पूर्व-दबावयुक्त',
    material: 'Steel',
  },

  // 2. Commercial RO Parts
  {
    id: 'COM-MEM-001',
    name: '4040 Industrial RO Membrane',
    name_hi: '4040 औद्योगिक आरओ मेम्ब्रेन',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Commercial RO Membranes',
    brand: 'Hydranautics',
    price: 9500,
    description: 'High-performance 4040 size industrial RO membrane for commercial water treatment plants. Offers superior salt rejection and high flow rates.',
    description_hi: 'वाणिज्यिक जल उपचार संयंत्रों के लिए उच्च-प्रदर्शन वाली 4040 आकार की औद्योगिक आरओ मेम्ब्रेन। बेहतर नमक अस्वीकृति और उच्च प्रवाह दर प्रदान करती है।',
    image: 'https://images.unsplash.com/photo-1614941408332-1b15b573d3a6d?q=80&w=2070&auto=format&fit=crop',
    features: '2400 GPD Capacity, High Salt Rejection, Low Pressure Operation',
    features_hi: '2400 GPD क्षमता, उच्च नमक अस्वीकृति, कम दबाव संचालन',
    gpd: 2400,
  },
  {
    id: 'COM-PUMP-001',
    name: '1 HP High Pressure Pump',
    name_hi: '1 HP हाई प्रेशर पंप',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'High-Pressure Pumps',
    brand: 'PureStream',
    price: 18000,
    discountPrice: 16500,
    description: 'Robust 1 HP multi-stage high-pressure pump for commercial RO systems up to 500 LPH. Built for continuous operation.',
    description_hi: '500 LPH तक के वाणिज्यिक आरओ सिस्टम के लिए मजबूत 1 HP मल्टी-स्टेज हाई-प्रेशर पंप। निरंतर संचालन के लिए निर्मित।',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: 'Stainless Steel Head, Continuous Duty Motor, High Flow',
    features_hi: 'स्टेनलेस स्टील हेड, निरंतर ड्यूटी मोटर, उच्च प्रवाह',
    voltage: '220V AC',
  },
  {
    id: 'COM-PUMP-002',
    name: 'Antiscalant Dosing Pump',
    name_hi: 'एंटीस्केलेंट डोजिंग पंप',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Dosing Pumps',
    brand: 'EcoWater',
    price: 7000,
    description: 'Electronic dosing pump for accurately injecting antiscalant solution into feed water for commercial RO systems.',
    description_hi: 'वाणिज्यिक आरओ सिस्टम के लिए फ़ीड पानी में एंटीस्केलेंट समाधान को सटीक रूप से इंजेक्ट करने के लिए इलेक्ट्रॉनिक डोजिंग पंप।',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: 'Adjustable Dosing Rate, Chemical Resistant, Precise Injection',
    features_hi: 'समायोज्य खुराक दर, रासायनिक प्रतिरोधी, सटीक इंजेक्शन',
    voltage: '220V AC',
  },
  {
    id: 'COM-VESSEL-001',
    name: 'FRP Pressure Vessel 4040',
    name_hi: 'एफआरपी प्रेशर वेसल 4040',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Pressure Vessels (FRP)',
    brand: 'Pentair',
    price: 11000,
    description: 'Durable and corrosion-resistant FRP pressure vessel for a single 4040 commercial RO membrane. End-port design.',
    description_hi: 'एकल 4040 वाणिज्यिक आरओ मेम्ब्रेन के लिए टिकाऊ और जंग-प्रतिरोधी एफआरपी प्रेशर वेसल। एंड-पोर्ट डिजाइन।',
    image: 'https://images.unsplash.com/photo-1596791882046-e575d5f99992?q=80&w=2070&auto=format&fit=crop',
    features: 'Corrosion Resistant, High Pressure Rating, End-Port Connectivity',
    features_hi: 'जंग प्रतिरोधी, उच्च दबाव रेटिंग, एंड-पोर्ट कनेक्टिविटी',
    material: 'FRP',
  },
  {
    id: 'COM-HOUSING-001',
    name: '20" Big Blue Filter Housing',
    name_hi: '20" बिग ब्लू फ़िल्टर हाउसिंग',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Big Blue Filter Housing',
    brand: 'AquaPure',
    price: 2200,
    description: '20-inch Big Blue housing for commercial pre-filters. Provides high flow rates and includes a pressure relief button.',
    description_hi: 'वाणिज्यिक प्री-फिल्टर के लिए 20-इंच बिग ब्लू हाउसिंग। उच्च प्रवाह दर प्रदान करता है और इसमें एक दबाव राहत बटन शामिल है।',
    image: 'https://images.unsplash.com/photo-1541701494587-b959e7825776?q=80&w=2070&auto=format&fit=crop',
    features: 'High Flow Capacity, Pressure Relief Button, Durable Polypropylene',
    features_hi: 'उच्च प्रवाह क्षमता, दबाव राहत बटन, टिकाऊ पॉलीप्रोपाइलीन',
    inletOutletSize: '1"',
  },
  {
    id: 'COM-METER-001',
    name: 'Rotameter Flow Meter (0-1000 LPH)',
    name_hi: 'रोटामीटर फ्लो मीटर (0-1000 LPH)',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Rotameter / Flow Meter',
    brand: 'Generic',
    price: 1500,
    description: 'Panel-mounted rotameter for accurately measuring permeate and reject water flow rates up to 1000 LPH.',
    description_hi: '1000 LPH तक परमीट और रिजेक्ट पानी के प्रवाह की दरों को सटीक रूप से मापने के लिए पैनल-माउंटेड रोटामीटर।',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop',
    features: 'Panel Mounted, Clear Acrylic Body, Accurate Readings',
    features_hi: 'पैनल माउंटेड, स्पष्ट ऐक्रेलिक बॉडी, सटीक रीडिंग',
  },
  {
    id: 'COM-GAUGE-001',
    name: 'Pressure Gauge (Glycerin Filled)',
    name_hi: 'प्रेशर गेज (ग्लिसरीन भरा हुआ)',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Pressure Gauges',
    brand: 'Generic',
    price: 600,
    description: 'Glycerin-filled pressure gauge for stable readings of pump and vessel pressure in commercial RO systems.',
    description_hi: 'वाणिज्यिक आरओ सिस्टम में पंप और पोत के दबाव की स्थिर रीडिंग के लिए ग्लिसरीन से भरा प्रेशर गेज।',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop',
    features: 'Stable Reading, Stainless Steel Case, 0-300 PSI Range',
    features_hi: 'स्थिर रीडिंग, स्टेनलेस स्टील केस, 0-300 PSI रेंज',
    material: 'Stainless Steel',
  },
  {
    id: 'COM-PANEL-001',
    name: 'RO Control Panel',
    name_hi: 'आरओ कंट्रोल पैनल',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Control Panels',
    brand: 'PureStream',
    price: 8500,
    description: 'Automatic control panel for commercial RO plants. Manages pumps, valves, and safety switches for seamless operation.',
    description_hi: 'वाणिज्यिक आरओ संयंत्रों के लिए स्वचालित नियंत्रण कक्ष। निर्बाध संचालन के लिए पंप, वाल्व और सुरक्षा स्विच का प्रबंधन करता है।',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop',
    features: 'Automated Logic, Overload Protection, Easy to Operate',
    features_hi: 'स्वचालित तर्क, अधिभार संरक्षण, संचालित करने में आसान',
    material: 'Metal',
  },
  {
    id: 'COM-FRAME-001',
    name: '250 LPH SS Skid Frame',
    name_hi: '250 LPH एसएस स्किड फ्रेम',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'SS Skids / RO Frames',
    brand: 'Generic',
    price: 12000,
    description: 'Pre-fabricated stainless steel skid for assembling a 250 LPH commercial RO plant. Corrosion-resistant and sturdy.',
    description_hi: '250 LPH वाणिज्यिक आरओ प्लांट को असेंबल करने के लिए पूर्व-निर्मित स्टेनलेस स्टील स्किड। जंग प्रतिरोधी और मजबूत।',
    image: 'https://images.unsplash.com/photo-1631049352163-3e21a8d1033b?q=80&w=1974&auto=format&fit=crop',
    features: 'SS 304 Material, Compact Design, Pre-Drilled Mounts',
    features_hi: 'एसएस 304 सामग्री, कॉम्पैक्ट डिजाइन, पूर्व-ड्रिल माउंट',
    material: 'Stainless Steel',
  },
  {
    id: 'COM-UV-001',
    name: '1000 LPH UV System',
    name_hi: '1000 LPH यूवी सिस्टम',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'UV Systems',
    brand: 'AquaPure',
    price: 15000,
    description: 'High-capacity UV sterilization system for 1000 LPH commercial applications. Features a stainless steel chamber for durability.',
    description_hi: '1000 LPH वाणिज्यिक अनुप्रयोगों के लिए उच्च क्षमता वाली यूवी नसबंदी प्रणाली। स्थायित्व के लिए एक स्टेनलेस स्टील कक्ष है।',
    image: 'https://images.unsplash.com/photo-1589283733355-c802693a7469?q=80&w=2014&auto=format&fit=crop',
    features: 'High Flow Rate, SS 304 Chamber, Kills 99.9% Microbes',
    features_hi: 'उच्च प्रवाह दर, एसएस 304 कक्ष, 99.9% रोगाणुओं को मारता है',
    material: 'Stainless Steel',
  },
  {
    id: 'COM-PUMP-003',
    name: '1 HP Raw Water Pump',
    name_hi: '1 HP कच्चा पानी पंप',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Raw Water Pump',
    brand: 'HydroFlow',
    price: 6000,
    description: '1 HP centrifugal pump for feeding raw water to commercial RO plants. Reliable performance for continuous use.',
    description_hi: 'वाणिज्यिक आरओ संयंत्रों में कच्चे पानी को खिलाने के लिए 1 एचपी केन्द्रापसारक पंप। निरंतर उपयोग के लिए विश्वसनीय प्रदर्शन।',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: 'High Suction Power, Durable Cast Iron Body, Thermal Overload Protection',
    features_hi: 'उच्च सक्शन पावर, टिकाऊ कच्चा लोहा शरीर, थर्मल अधिभार संरक्षण',
    voltage: '220V AC',
  },

  // 3. RO Accessories & Installation Tools
  {
    id: 'ACC-TDS-001',
    name: 'Pocket TDS Meter',
    name_hi: 'पॉकेट टीडीएस मीटर',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'TDS Meters',
    brand: 'Generic',
    price: 350,
    discountPrice: 300,
    description: 'Handy digital TDS meter to check the quality of water and performance of your RO system. Includes temperature sensor.',
    description_hi: 'आपके आरओ सिस्टम के पानी की गुणवत्ता और प्रदर्शन की जांच के लिए आसान डिजिटल टीडीएस मीटर। तापमान सेंसर शामिल है।',
    image: 'https://images.unsplash.com/photo-1628149849209-968568b65553?q=80&w=2070&auto=format&fit=crop',
    features: 'Accurate Readings, Pocket-Sized, Auto-off Function',
    features_hi: 'सटीक रीडिंग, पॉकेट-आकार, ऑटो-ऑफ फ़ंक्शन',
  },
  {
    id: 'ACC-TOOL-001',
    name: 'Housing Wrench / Spanner',
    name_hi: 'हाउसिंग रिंच / स्पैनर',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'Wrenches / Tools',
    brand: 'Generic',
    price: 120,
    description: 'Durable plastic wrench for opening and tightening standard domestic filter and membrane housings.',
    description_hi: 'मानक घरेलू फिल्टर और मेम्ब्रेन हाउसिंग को खोलने और कसने के लिए टिकाऊ प्लास्टिक रिंच।',
    image: 'https://images.unsplash.com/photo-1558611848-ea515b5e39c4?q=80&w=2070&auto=format&fit=crop',
    features: 'Fits Standard Housings, Durable Plastic, Essential Tool',
    features_hi: 'मानक हाउसिंग में फिट बैठता है, टिकाऊ प्लास्टिक, आवश्यक उपकरण',
    material: 'Plastic',
  },
  {
    id: 'ACC-TOOL-002',
    name: 'RO Pipe Cutter',
    name_hi: 'आरओ पाइप कटर',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'Pipe Cutter',
    brand: 'Generic',
    price: 180,
    description: 'Specialized tool for making clean, square cuts on 1/4" and 3/8" RO tubing, ensuring leak-free connections.',
    description_hi: '1/4" और 3/8" आरओ ट्यूबिंग पर साफ, चौकोर कट बनाने के लिए विशेष उपकरण, लीक-मुक्त कनेक्शन सुनिश्चित करता है।',
    image: 'https://images.unsplash.com/photo-1558611848-ea515b5e39c4?q=80&w=2070&auto=format&fit=crop',
    features: 'Clean Cuts, For 1/4" & 3/8" Pipes, Easy to Use',
    features_hi: 'साफ कट, 1/4" और 3/8" पाइप के लिए, उपयोग में आसान',
  },
  {
    id: 'ACC-SEAL-001',
    name: 'O-Ring Seal Kit',
    name_hi: 'ओ-रिंग सील किट',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'O-Rings & Seal Kits',
    brand: 'Generic',
    price: 200,
    description: 'A complete set of O-rings for domestic filter housings and membrane housings to prevent leaks.',
    description_hi: 'लीक को रोकने के लिए घरेलू फिल्टर हाउसिंग और मेम्ब्रेन हाउसिंग के लिए ओ-रिंग का एक पूरा सेट।',
    image: 'https://images.unsplash.com/photo-1543292489-0f475739c316?q=80&w=2070&auto=format&fit=crop',
    features: 'Universal Kit, High-Quality Rubber, Prevents Leaks',
    features_hi: 'यूनिवर्सल किट, उच्च गुणवत्ता वाला रबर, लीक को रोकता है',
  },
  {
    id: 'ACC-CAB-001',
    name: 'RO Cabinet Body (Wall-Mount)',
    name_hi: 'आरओ कैबिनेट बॉडी (वॉल-माउंट)',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'RO Cabinet Body',
    brand: 'PureStream',
    price: 2500,
    description: 'A stylish and durable cabinet/body for assembling a complete RO unit. Features a modern design with an integrated tank.',
    description_hi: 'एक पूर्ण आरओ इकाई को असेंबल करने के लिए एक स्टाइलिश और टिकाऊ कैबिनेट/बॉडी। एकीकृत टैंक के साथ एक आधुनिक डिजाइन है।',
    image: 'https://images.unsplash.com/photo-1629840282877-1718153b6f9e?q=80&w=1964&auto=format&fit=crop',
    features: 'Modern Design, Integrated Tank, Food-Grade Plastic',
    features_hi: 'आधुनिक डिजाइन, एकीकृत टैंक, फूड-ग्रेड प्लास्टिक',
    material: 'ABS',
  },
  {
    id: 'ACC-TAPE-001',
    name: 'Teflon Tape',
    name_hi: 'टेफ्लॉन टेप',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'Teflon Tape',
    brand: 'Generic',
    price: 20,
    description: 'Thread seal tape for ensuring leak-proof connections on threaded fittings in RO systems.',
    description_hi: 'आरओ सिस्टम में थ्रेडेड फिटिंग पर लीक-प्रूफ कनेक्शन सुनिश्चित करने के लिए थ्रेड सील टेप।',
    image: 'https://images.unsplash.com/photo-1596463284487-32898f060783?q=80&w=1954&auto=format&fit=crop',
    features: 'Seals Threads, Prevents Leaks, Easy to Use',
    features_hi: 'धागे सील करता है, लीक रोकता है, उपयोग में आसान',
  },

  // 4. Complete RO Systems
  {
    id: 'SYS-DOM-001',
    name: '7-Stage Domestic RO System',
    name_hi: '7-स्टेज घरेलू आरओ सिस्टम',
    mainCategory: 'Complete RO Systems',
    subcategory: 'Domestic RO Systems',
    brand: 'AquaPure',
    price: 12000,
    discountPrice: 9999,
    description: 'A complete 7-stage RO+UV+UF+TDS Adjuster water purifier. Provides 100% pure, healthy, and tasty water.',
    description_hi: 'एक पूर्ण 7-चरण आरओ+यूवी+यूएफ+टीडीएस एडजस्टर जल शोधक। 100% शुद्ध, स्वस्थ और स्वादिष्ट पानी प्रदान करता है।',
    image: 'https://images.unsplash.com/photo-1629840282877-1718153b6f9e?q=80&w=1964&auto=format&fit=crop',
    features: 'Multi-Stage Purification, Includes UV & UF, Wall-Mountable',
    features_hi: 'बहु-स्तरीय शुद्धिकरण, यूवी और यूएफ शामिल, दीवार पर लगाया जा सकता है',
    gpd: 80,
  },
  {
    id: 'SYS-DOM-002',
    name: 'Under-Sink RO System',
    name_hi: 'अंडर-सिंक आरओ सिस्टम',
    mainCategory: 'Complete RO Systems',
    subcategory: 'Under-Sink Units',
    brand: 'EcoWater',
    price: 15000,
    description: 'Compact under-sink RO system perfect for modular kitchens. Saves counter space while providing pure water on demand.',
    description_hi: 'मॉड्यूलर किचन के लिए एकदम सही कॉम्पैक्ट अंडर-सिंक आरओ सिस्टम। मांग पर शुद्ध पानी प्रदान करते हुए काउंटर स्पेस बचाता है।',
    image: 'https://images.unsplash.com/photo-1629840282877-1718153b6f9e?q=80&w=1964&auto=format&fit=crop',
    features: 'Space Saving Design, Easy Installation, Separate Faucet Included',
    features_hi: 'जगह बचाने वाला डिजाइन, आसान स्थापना, अलग नल शामिल',
    gpd: 75,
  },
  {
    id: 'SYS-COM-001',
    name: '100 LPH Commercial RO Plant',
    name_hi: '100 LPH वाणिज्यिक आरओ प्लांट',
    mainCategory: 'Complete RO Systems',
    subcategory: 'Commercial RO Plants',
    brand: 'PureStream',
    price: 45000,
    description: 'A complete 100 Liters Per Hour commercial RO plant, mounted on a stainless steel skid. Ideal for small offices, restaurants, and schools.',
    description_hi: 'एक पूर्ण 100 लीटर प्रति घंटे का वाणिज्यिक आरओ प्लांट, जो एक स्टेनलेस स्टील स्किड पर लगा है। छोटे कार्यालयों, रेस्तरां और स्कूलों के लिए आदर्श।',
    image: 'https://images.unsplash.com/photo-1631049352163-3e21a8d1033b?q=80&w=1974&auto=format&fit=crop',
    features: 'SS Skid Mounted, Fully Automatic, High Recovery Rate',
    features_hi: 'एसएस स्किड माउंटेड, पूरी तरह से स्वचालित, उच्च रिकवरी दर',
    material: 'Stainless Steel',
  },
  {
    id: 'SYS-COM-002',
    name: '500 LPH Industrial Water Purifier',
    name_hi: '500 LPH औद्योगिक जल शोधक',
    mainCategory: 'Complete RO Systems',
    subcategory: 'Industrial Water Purifiers',
    brand: 'HydroFlow',
    price: 120000,
    description: 'Heavy-duty 500 LPH industrial RO plant with pre-treatment. Designed for factories and large commercial establishments.',
    description_hi: 'प्री-ट्रीटमेंट के साथ हेवी-ड्यूटी 500 LPH औद्योगिक आरओ प्लांट। कारखानों और बड़े वाणिज्यिक प्रतिष्ठानों के लिए डिज़ाइन किया गया।',
    image: 'https://images.unsplash.com/photo-1631049352163-3e21a8d1033b?q=80&w=1974&auto=format&fit=crop',
    features: 'Includes Softener, High-Pressure Pump, Control Panel',
    features_hi: 'सॉफ़्नर शामिल, उच्च दबाव पंप, नियंत्रण कक्ष',
    material: 'Stainless Steel',
  },

  // 5. Service Kits & Combo Packs
  {
    id: 'KIT-SVC-001',
    name: 'Annual Maintenance Kit',
    name_hi: 'वार्षिक रखरखाव किट',
    mainCategory: 'Service Kits & Combo Packs',
    subcategory: 'Annual Maintenance Kits',
    brand: 'Generic',
    price: 2500,
    discountPrice: 2200,
    description: 'A complete one-year service kit for domestic RO systems. Includes 3 spun filters, 1 sediment, 1 carbon, 1 post-carbon, and 1 membrane.',
    description_hi: 'घरेलू आरओ सिस्टम के लिए एक पूर्ण एक-वर्षीय सेवा किट। इसमें 3 स्पन फिल्टर, 1 सेडिमेंट, 1 कार्बन, 1 पोस्ट-कार्बन और 1 मेम्ब्रेन शामिल हैं।',
    image: 'https://images.unsplash.com/photo-1629849247657-611a8d1633f7?q=80&w=2070&auto=format=fit&crop',
    features: 'Full Year Supply, All Filters Included, Cost-Effective',
    features_hi: 'पूरे साल की आपूर्ति, सभी फिल्टर शामिल, लागत प्रभावी',
  },
  {
    id: 'KIT-FLT-001',
    name: '3-Stage Filter Combo Pack',
    name_hi: '3-स्टेज फ़िल्टर कॉम्बो पैक',
    mainCategory: 'Service Kits & Combo Packs',
    subcategory: 'Filter Combo Packs',
    brand: 'Generic',
    price: 800,
    description: 'A basic filter replacement kit containing one spun filter, one inline sediment filter, and one inline carbon filter.',
    description_hi: 'एक बुनियादी फिल्टर प्रतिस्थापन किट जिसमें एक स्पन फिल्टर, एक इनलाइन सेडिमेंट फिल्टर और एक इनलाइन कार्बन फिल्टर होता है।',
    image: 'https://images.unsplash.com/photo-1629849247657-611a8d1633f7?q=80&w=2070&auto=format=fit&crop',
    features: 'Essential Filters, For 6-Month Service, Fits Most ROs',
    features_hi: 'आवश्यक फिल्टर, 6 महीने की सेवा के लिए, अधिकांश आरओ में फिट बैठता है',
  },
  {
    id: 'KIT-INS-001',
    name: 'Startup Installation Kit',
    name_hi: 'स्टार्टअप इंस्टॉलेशन किट',
    mainCategory: 'Service Kits & Combo Packs',
    subcategory: 'Startup Installation Kits',
    brand: 'Generic',
    price: 650,
    description: 'Everything you need for a new RO installation. Includes pipe, connectors, tap adapter, Teflon tape, and a float valve.',
    description_hi: 'एक नए आरओ इंस्टॉलेशन के लिए आपको जो कुछ भी चाहिए। इसमें पाइप, कनेक्टर, टैप एडॉप्टर, टेफ्लॉन टेप और एक फ्लोट वाल्व शामिल है।',
    image: 'https://images.unsplash.com/photo-1558611848-ea515b5e39c4?q=80&w=2070&auto=format&fit=crop',
    features: 'Complete Installation Set, High-Quality Components, Saves Time',
    features_hi: 'पूर्ण स्थापना सेट, उच्च गुणवत्ता वाले घटक, समय बचाता है',
  },
  {
    id: 'KIT-BRD-001',
    name: 'Kent Compatible Full Kit',
    name_hi: 'केंट संगत पूर्ण किट',
    mainCategory: 'Service Kits & Combo Packs',
    subcategory: 'Brand-Specific Kits',
    brand: 'Kent',
    price: 2800,
    description: 'A complete service kit with parts compatible with most Kent RO models. Includes sediment, carbon, UF, and RO membrane.',
    description_hi: 'अधिकांश केंट आरओ मॉडल के साथ संगत भागों के साथ एक पूर्ण सेवा किट। इसमें सेडिमेंट, कार्बन, यूएफ और आरओ मेम्ब्रेन शामिल हैं।',
    image: 'https://images.unsplash.com/photo-1629849247657-611a8d1633f7?q=80&w=2070&auto=format=fit&crop',
    features: 'For Kent Models, High-Quality Spares, Includes Membrane',
    features_hi: 'केंट मॉडल के लिए, उच्च गुणवत्ता वाले पुर्जे, मेम्ब्रेन शामिल',
  },
  {
    id: 'DOM-MEM-002',
    name: 'Filmtec 75 GPD RO Membrane',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'RO Membranes',
    brand: 'Filmtec',
    price: 2200,
    description: 'Genuine Dow Filmtec 75 GPD membrane, the industry standard for performance and reliability.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'Genuine Dow Product, 99% Rejection, Trusted Performance',
    gpd: 75,
    material: 'Polyamide Thin-Film Composite',
  },
  {
    id: 'DOM-FILTER-004',
    name: 'Hollow Fiber UF Membrane',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'UF Membranes',
    brand: 'Generic',
    price: 600,
    description: 'Ultra-filtration membrane that removes bacteria and cysts without removing essential minerals.',
    image: 'https://images.unsplash.com/photo-1621253459146-2313ce8f1547?q=80&w=2070&auto=format&fit=crop',
    features: 'Removes Bacteria, Retains Minerals, No Electricity Required',
    inletOutletSize: '1/4"',
  },
  {
    id: 'DOM-PUMP-002',
    name: '75 GPD Booster Pump (36V)',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Pump (Booster Pump)',
    brand: 'PureStream',
    price: 2800,
    description: 'High-power 36V booster pump for 75 GPD systems, providing higher pressure and better performance.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: 'Higher Pressure, For 36V SMPS, Improved Purification',
    gpd: 75,
    voltage: '36V',
  },
  {
    id: 'DOM-HOUSING-002',
    name: '10" Transparent Pre-Filter Housing',
    mainCategory: 'Domestic RO Parts',
    subcategory: 'Filter Housing',
    brand: 'EcoWater',
    price: 700,
    description: 'Transparent 10" housing for pre-filters, allowing easy visual inspection of the filter cartridge.',
    image: 'https://images.unsplash.com/photo-1541701494587-b959e7825776?q=80&w=2070&auto=format&fit=crop',
    features: 'See-through design, Food-grade plastic, Includes wrench',
    material: 'Plastic',
    color: 'Transparent',
  },
  {
    id: 'COM-MEM-002',
    name: '8040 Industrial RO Membrane',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'Commercial RO Membranes',
    brand: 'CSM',
    price: 25000,
    description: 'High-rejection 8040 brackish water membrane for large-scale industrial plants.',
    image: 'https://images.unsplash.com/photo-1614941408332-1b15b573d3a6d?q=80&w=2070&auto=format&fit=crop',
    features: 'High Flow Rate, >99% Salt Rejection, Durable Construction',
    gpd: 10000,
  },
  {
    id: 'COM-PUMP-004',
    name: '2 HP Multi-Stage Booster Pump',
    mainCategory: 'Commercial RO Parts',
    subcategory: 'High-Pressure Pumps',
    brand: 'PureStream',
    price: 25000,
    description: 'A powerful 2 HP vertical multi-stage pump for 1000-2000 LPH RO plants.',
    image: 'https://images.unsplash.com/photo-1616037192285-1d4a6a5b2e0c?q=80&w=1974&auto=format&fit=crop',
    features: 'Vertical Design, Stainless Steel Impellers, High Head',
    voltage: '415V 3-Phase',
  },
  {
    id: 'ACC-TOOL-003',
    name: 'Housing Wrench for Big Blue',
    mainCategory: 'RO Accessories & Tools',
    subcategory: 'Wrenches / Tools',
    brand: 'Generic',
    price: 350,
    description: 'Heavy-duty spanner for 10" and 20" Big Blue commercial filter housings.',
    image: 'https://images.unsplash.com/photo-1558611848-ea515b5e39c4?q=80&w=2070&auto=format&fit=crop',
    features: 'Heavy-Duty Plastic, Fits Jumbo Housings, Essential for Service',
    material: 'Plastic',
  },
  {
    id: 'KIT-BRD-002',
    name: 'Aquaguard Compatible Full Kit',
    mainCategory: 'Service Kits & Combo Packs',
    subcategory: 'Brand-Specific Kits',
    brand: 'Aquaguard',
    price: 2600,
    description: 'Full service kit compatible with most Aquaguard RO models. Includes Chemi-block, sediment, and RO membrane.',
    image: 'https://images.unsplash.com/photo-1629849247657-611a8d1633f7?q=80&w=2070&auto=format=fit&crop',
    features: 'For Aquaguard Models, Includes Chemi-block, Cost-Effective',
  }
];

    