# Configuration for Netlify

[build]
  # This command is run to build the project.
  command = "npm run build"

  # This is the directory that Netlify will deploy.
  publish = ".next"
  
  # Environment variables for the build
  [build.environment]
    # Omit these keys from Netlify's secret scanning to prevent build failures.
    # These are necessary for the application to build and function correctly.
    SECRETS_SCAN_OMIT_KEYS = "FIREBASE_SERVICE_ACCOUNT_BASE64,GEMINI_API_KEY,IMAGEKIT_PRIVATE_KEY,IMAGEKIT_PUBLIC_KEY,NEXT_PUBLIC_FIREBASE_API_KEY"

[dev]
  # This is the command that will be run when you run `netlify dev`
  command = "npm run dev"
  # The port for the local development server.
  port = 9002
  # The port for the framework's development server.
  targetPort = 9002
  # Automatically start the framework's development server.
  autoLaunch = true

[[plugins]]
  # Essential plugin for Next.js on Netlify
  package = "@netlify/plugin-nextjs"
